name: x_unique_list
description: "A Flutter package that provides a list with unique elements based on a custom uniqueness condition."
version: 1.0.1
license: MIT
homepage: https://github.com/Ahmad-Nour-Haidar
repository: https://github.com/Ahmad-Nour-Haidar/x-unique-list

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0


#author: Ahmad Nour Haidar
# or repository if you prefer
#environment:
#  sdk: ^3.5.0
#  flutter: ">=1.17.0"